apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  
  resources:
    requests:
      storage: 2Gi  
